hyperparamters:
  patience : 4
  batch_size : 128
  epochs : 30
  learning_rate : 0.001
  model_name : 'resnet50'
  pretrained : True

data:
  train_dir : '../data/Images/Train'
  val_dir : '../data/Images/Validate'
  test_dir : '../data/Images/Test'
