hyperparamters:
  patience : 4
  batch_size : 128
  epochs : 30
  learning_rate : 0.001
  weight_decay : 0.0
  model_name : 'inception_v4'
  pretrained : True

hardware:
  cpus: 32
  device: 'cuda'
 
data:
  train_dir : '../data/Images/Train'
  val_dir : '../data/Images/Validate'
  test_dir : '../data/Images/Test'
